publish results

diff --git a/.github/workflows/CI-pipeline.yml b/.github/workflows/CI-pipeline.yml
--- a/.github/workflows/CI-pipeline.yml
+++ b/.github/workflows/CI-pipeline.yml
@@ -40,4 +40,12 @@ jobs:
 
       - name: Run Unit Test
         if: ${{ true }}
-        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=ShoppingCart.UnitTestsResults.trx"
+        run: dotnet test --no-restore --verbosity minimal --logger "trx;LogFileName=ShoppingCart.UnitTestsResults.trx"
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: dotnet Tests            # Name of the check run which will be created
+          path: ShoppingCart.UnitTestsResults.trx    # Path to test results
+          reporter: dotnet-trx          # Format of test results
